keys:
  - &gunnar 8821c0948c4286beb2fe9308bf48b4e0c22b5c18
  - &desktop 7350bbea7594e8ddd9b828e14c964c5c9a7e6440
  - &laptop d76eacd20fe0f56611b5ecbebe21c55b7b3e8b0a
  - &server ef9ecff4db2e0da521624600ce5e3e8f09cc709a

creation_rules:
  - path_regex: secrets/[^/]+$
    key_groups:
      - pgp:
        - *gunnar
        - *desktop
        - *laptop
        - *server
