# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  modulesPath,
  ...
}:
{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  systemd.services.zfs-load-key-tank = {
    description = "Load ZFS encryption key for tank";
    before = [ "zfs-mount.service" ];
    after = [
      "zfs-import.target"
      "boot.mount"
    ];
    requires = [ "zfs-import.target" ];
    wants = [
      "zfs-import.target"
      "boot.mount"
    ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
    };
    script = ''
      zpool import -N tank || true
      zfs load-key -L file /boot/zfs.key tank
    '';
  };

  boot = {
    initrd = {
      systemd.enable = true;
      availableKernelModules = [
        "ehci_pci"
        "ahci"
        "mpt3sas"
        "nvme"
        "usb_storage"
        "usbhid"
      ];
    };
    zfs.extraPools = [ "tank" ];
    kernelModules = [ "kvm-intel" ];
    extraModulePackages = [ ];
  };

  fileSystems = {
    "/" = {
      device = "/dev/disk/by-label/NIXROOT";
      fsType = "ext4";
    };

    "/boot" = {
      device = "/dev/disk/by-label/NIXBOOT";
      fsType = "vfat";
      options = [
        "fmask=0022"
        "dmask=0022"
      ];
    };
  };

  swapDevices = [ ];
  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
