# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  modulesPath,
  ...
}:
{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  services.lvm = {
    enable = true;
    boot.thin.enable = true;
  };

  boot = {
    swraid = {
      enable = true;
      mdadmConf = ''
        ARRAY /dev/md/0  metadata=1.2 UUID=8496037f:04ddcd65:496e9628:a9891237
          MAILADDR admin@ghov.net
      '';
    };

    initrd = {
      systemd.enable = true;
      availableKernelModules = [
        "ehci_pci"
        "ahci"
        "mpt3sas"
        "nvme"
        "usb_storage"
        "usbhid"
        "sd_mod"
        "sr_mod"
        "dm_thin_pool"
      ];

      luks.devices."encrypted_raid" = {
        device = "/dev/md0";
        preLVM = true;
      };

      services.lvm.enable = true;
    };
    kernelModules = [ "kvm-intel" ];
    extraModulePackages = [ ];
  };

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/98ae9690-fe34-4fe6-a8d9-6bc97d083d26";
    fsType = "ext4";
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/455C-EF79";
    fsType = "vfat";
    options = [
      "fmask=0022"
      "dmask=0022"
    ];
  };

  fileSystems."/media" = {
    device = "/dev/disk/by-label/MEDIA";
    fsType = "ext4";
    options = [
      "defaults"
      "noatime"
      "x-systemd.device-timeout=60s"
      "x-systemd.after=lvm2-monitor.service"
    ];
  };

  fileSystems."/data" = {
    device = "/dev/disk/by-label/DATA";
    fsType = "ext4";
    options = [
      "defaults"
      "noatime"
      "x-systemd.device-timeout=60s"
      "x-systemd.after=lvm2-monitor.service"
    ];
  };

  swapDevices = [ ];
  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
