# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  modulesPath,
  ...
}:
{
  imports = [ (modulesPath + "/installer/scan/not-detected.nix") ];

  boot = {
    extraModulePackages = [ config.boot.kernelPackages.msi-ec ];
    extraModprobeConfig = "options msi-ec debug=true";
    initrd = {
      systemd = {
        tpm2.enable = true;
        enable = true;
        emergencyAccess = true;
      };

      kernelModules = [
        "amdgpu"
        "nvme"
        "xhci_pci"
        "usbhid"
        "usb_storage"
        "sd_mod"
        "tpm_crb"
        "tpm_tis"
        "msi-ec"
      ];
      luks.devices = {
        usbkey = {
          device = "/dev/disk/by-uuid/51038c86-41d6-4ce5-92d5-76e07186c503";
          crypttabExtraOpts = [
            "tpm2-device=auto"
            "nofail"
            "x-systemd.device-timeout=10s"
          ];
        };
        cryptroot = {
          device = "/dev/disk/by-uuid/680a0c22-aca0-4739-b515-691e1de8f5d0";
          keyFile = "/root.key:/dev/mapper/usbkey";
          crypttabExtraOpts = [ "keyfile-timeout=10s" ];
        };
      };
    };
  };

  fileSystems = {
    "/" = {
      device = "/dev/disk/by-label/NIXROOT";
      fsType = "ext4";
    };

    "/home" = {
      device = "/dev/disk/by-label/NIXHOME";
      fsType = "ext4";
    };

    "/boot" = {
      device = "/dev/disk/by-label/NIXBOOT";
      fsType = "vfat";
      options = [
        "fmask=0077"
        "dmask=0077"
      ];
    };
  };

  swapDevices = [ { device = "/dev/disk/by-label/NIXSWAP"; } ];
  networking.useDHCP = lib.mkDefault true;
  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
