# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  modulesPath,
  ...
}: {
  imports = [(modulesPath + "/installer/scan/not-detected.nix")];

  boot = {
    initrd.availableKernelModules = [
      "nvme"
      "xhci_pci"
      "ahci"
      "usbhid"
      "usb_storage"
      "sd_mod"
    ];
    initrd.kernelModules = [];
    kernelModules = ["amdgpu"];
    extraModulePackages = [];
    supportedFilesystems = ["ntfs"];
    tmp.tmpfsSize = "75%";
  };

  fileSystems = {
    "/" = {
      device = "/dev/disk/by-uuid/3e395b47-af45-4a78-b87e-a23586793b6a";
      fsType = "ext4";
    };

    "/boot" = {
      device = "/dev/disk/by-uuid/D829-A283";
      fsType = "vfat";
      options = [
        "fmask=0077"
        "dmask=0077"
      ];
    };

    "/home/gunnar/ssd" = {
      device = "/dev/disk/by-id/ata-Samsung_SSD_860_QVO_2TB_S4PHNF0M701338E-part1";
      fsType = "ntfs-3g";
      options = ["rw" "uid=1000"];
    };
  };

  networking.useDHCP = lib.mkDefault true;
  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
